# Start from the latest golang base image
FROM golang:{{.GoVersion}} AS builder

# Set the Current Working Directory inside the container
WORKDIR /build

# Copy the source from the current directory to the Working Directory inside the container
COPY . .

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod tidy

# Build the Go app
RUN go build -o {{.RunTaskName}} cmd/main.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest

WORKDIR /opt/rtfm/

# Download and install the Amazon Root CA certificate
RUN curl -o Amazon-RSA-2048-M03.pem https://www.amazontrust.com/repository/Amazon-RSA-2048-M03.pem && \
    cp Amazon-RSA-2048-M03.pem /etc/pki/ca-trust/source/anchors/ && \
    update-ca-trust

# Copy the binary from the builder stage
COPY --from=builder /build/{{.RunTaskName}} .

# Expose port 8080 and 8443 to the outside world
EXPOSE 8080 8443

# Command to run the executable
CMD ["./{{.RunTaskName}}"]