name: Build and Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.22'

    - name: Test
      run: go test ./...
        
    - name: Build for Linux
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -v -o rtfm-linux-amd64 ./cmd/rtfm

    - name: Build for macOS (Apple Silicon)
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -v -o rtfm-darwin-amd64 ./cmd/rtfm

    - name: Create and Upload Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          rtfm-darwin-arm64
          rtfm-linux-amd64